// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zivcgyrqekllqtmxuwyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppdmNneXJxZWtsbHF0bXh1d3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTAwNDIsImV4cCI6MjA2NTMyNjA0Mn0.6yyxMSwCPgpjXceUdJyEaj5KyjLU-a9_XfkmX2uIOQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);